### ISSUE TITLE
SyntaxError in api.py on Python 2.7

### ISSUE THREAD

**Issue by ninadsp** [hiway/pcogram#1]
Running `pcogram` on an El Capitan system after installing the client gives a syntax error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/pcogram", line 9, in <module>
    load_entry_point('pcogram==0.1.0', 'console_scripts', 'pcogram')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/pcogram-0.1.0-py2.7.egg/pcogram/__init__.py", line 6, in <module>
    from .api import PcogramAPI
  File "/Library/Python/2.7/site-packages/pcogram-0.1.0-py2.7.egg/pcogram/api.py", line 22
    headers.update({'Authorization': f'Bearer {self.token}'})
                                                          ^
SyntaxError: invalid syntax
```

Python information:
```
$ python --version
Python 2.7.10
```

**Comment by hiway** [comment]
Ah! Ah! Too used to Python3.6's fantastic f-strings ^_^

Fixing.
